-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 17:01:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gade` DEFAULT CHARACTER SET utf8 ;
USE `Gade` ;

-- -----------------------------------------------------
-- Table `Gade`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gade`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `imagem` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tamanho` VARCHAR(10) NOT NULL,
  `fornecedor` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gade`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gade`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `dataPagamento` DATE NOT NULL,
  `chavePix` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gade`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gade`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `perfil` VARCHAR(30) NOT NULL DEFAULT 'Cliente' COMMENT 'Administrador\nCliente',
  `cpf` VARCHAR(14) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(50) NOT NULL,
  `ncasa` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gade`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gade`.`Carrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `estatos` VARCHAR(45) NOT NULL COMMENT 'Aberto\nFinalizado\nCanccelado\nPendente',
  `Usuario_id_Usuario` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_Carrinho_Usuario1_idx` (`Usuario_id_Usuario` ASC)    ,
  INDEX `fk_Carrinho_Produto1_idx` (`Produto_idProduto` ASC)    ,
  CONSTRAINT `fk_Carrinho_Usuario1`
    FOREIGN KEY (`Usuario_id_Usuario`)
    REFERENCES `Gade`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrinho_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `Gade`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gade`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gade`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `quantidadePedidos` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Produto_codigoProduto` INT NOT NULL,
  `Pagamento_idPagamento` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Usuario1_idx` (`Usuario_idUsuario` ASC)    ,
  INDEX `fk_Pedidos_Produto1_idx` (`Produto_codigoProduto` ASC)    ,
  INDEX `fk_Pedidos_Pagamento1_idx` (`Pagamento_idPagamento` ASC)    ,
  CONSTRAINT `fk_Pedidos_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Gade`.`Usuario` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Produto1`
    FOREIGN KEY (`Produto_codigoProduto`)
    REFERENCES `Gade`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Pagamento1`
    FOREIGN KEY (`Pagamento_idPagamento`)
    REFERENCES `Gade`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
